
# Stage 1: Build the NestJS application
FROM node:16  AS builder

WORKDIR /app

# Copy package.json and package-lock.json for npm install
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the NestJS application
RUN npm run build

from builder as dev

# Expose port 5000
EXPOSE 5001


# Command to run the NestJS application
CMD ["npm", "run", "start:dev"]


# Stage 2: Create the production image
FROM node:16-alpine as prod

WORKDIR /app

# Copy the built application from the previous stage
COPY --from=builder /app/dist ./dist
COPY package*.json ./

# Install only production dependencies
RUN npm install --only=production

# Expose port 5000
EXPOSE 5001

# Command to run the NestJS application
CMD ["node", "dist/main.js"]